import Head from "next/head";
import Header from "components/Header";
import Feed from "components/Feed";
import Sidebar from "@/components/Sidebar";
import NavbarFlow from "@/components/NavbarFlow";
import Dropdown from "components/Dropdown";




export default function Home() {
  return (
    <div>
      <Head>
        <title>gems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <NavbarFlow/> */}
      

      <Header />

      <main className="flex">
        {/* {sidebar} */}
        {/* <Sidebar/> */}
        {/* {feed} */}
        <Feed/>
        <Dropdown/>
        {/* {widgets} */}
        {/* <Sidebar/> */}
        

      </main>
    </div>
  );
}
