import Head from "next/head";
import Header from "components/Header";
import Feed from "components/Feed";
import Sidebar from "@/components/Sidebar";
import SidebarRight from "@/components/SidebarRight";
import NavbarFlow from "@/components/NavbarFlow";
import NewSidebarLeft from "@/components/NewSidebar/NewSidebarLeft";
import BottomNav from "@/components/BottomNav";
import Guest from "@/components/Guest";
import { useState } from "react";
import { getSession, useSession, signIn, signOut } from "next-auth/react";

// import Dropdown from "components/Dropdown";

export default function Home() {
  const {data: session} = useSession();

  return (
    <div>
      <Head>
        <title>gems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? User({ session }) : Guest()}
    </div>
  );
}

function User({ session }) {
  return (
    <div>

      <Header />
      <main className="flex">
        {/* <Sidebar /> */}
        {/* <NewSidebarLeft />  */}
        <Feed />
        {/* <Dropdown /> */}
        {/* <SidebarRight /> */}
      </main>
      <BottomNav />
      <h1>{session.user.name}</h1>
      <h1>{session.user.email}</h1>
    <button className="text-blue-500" onClick={signOut}>Sign out</button>

    </div>
  );
}

export async function getServerSideProps({req}){
  const session=await getSession({req})
  if(!session){
    return{
      redirect:{
        destination:'/login',
        permanent: false
      }
    }
  }
  return {
    props:{ session}
  }
}